AllCops:
  TargetRubyVersion: 3.0

Style/SymbolArray:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
